# Use root/example as user/password credentials
version: '3.1'

secrets:
  db_root_password:
    external: true
  db_user:
    external: true
  db_password:
    external: true

services:
  app:
    image: erdlet/covistat:b20ceb2
    restart: on-failure
    secrets:
      - db_user
      - db_password
    environment:
      DB_POOL_NAME: covistat-pool
      DB_JNDI_NAME: java:/jdbc/covistat
      DB_URI: jdbc:mariadb://db/covistat
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 8081:8080

  db:
    image: mariadb
    restart: on-failure
    secrets:
      - db_root_password
      - db_user
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: covistat
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata: