# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: erdlet/covistat:latest 
    restart: on-failure
    environment:
      DB_POOL_NAME: covistat-pool
      DB_JNDI_NAME: java:/jdbc/covistat
      DB_URI: jdbc:mariadb://db/covistat
      DB_USER: covistat 
      DB_PASSWORD: covistatPw 
    ports:
      - 8080:8080

  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: covistatRootPw 
      MYSQL_USER: covistat 
      MYSQL_PASSWORD: covistatPw 
      MYSQL_DATABASE: covistat
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
