# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: covistat
      MYSQL_PASSWORD: covistatPw
      MYSQL_DATABASE: covistat
    ports:
      - 3306:3306
