name: CoviStat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile with Maven
      run: mvn -B compile --file pom.xml
    - name: Run Unit Tests
      run: mvn -B test --file pom.xml
